version: '3'

services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    volumes:
      - ./api:/api
    ports:
      - "80:80"
      - "443:443"
    entrypoint: /api/docker-entrypoint.sh
    command: "dotnet run --project Cukeness.Api/Cukeness.Api.csproj"
  
  runner:
    build:
      context: ./runner
      dockerfile: ./Dockerfile
    volumes:
      - ./features:/work/features
      - ./runner/configuration:/work/features/configuration
    
  step-server:
    build:
      context: ./step-server
      dockerfile: ./Dockerfile
    volumes:
      - ./step-server:/step-server
    command: "dotnet run --project /step-server/server/server.csproj"

    